name: image_editor_plus
description: fork https://github.com/hsbijarniya/image_editor_plus 0.2.1
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ">=1.1.2 <2.0.0"
  screenshot: ^3.0.0
  flutter_colorpicker: ^1.1.0
  extended_image: ^8.2.1
  image: ^4.2.0
  image_editor: ^1.5.1
  colorfilter_generator: ^0.0.8
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
