name: image_editor_plus
description: fork https://github.com/hsbijarniya/image_editor_plus 0.2.1
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.5+3
  screenshot: ^2.1.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.0.2
  image: ^4.0.15
  image_editor: ^1.0.2
  colorfilter_generator: ^0.0.8
  flutter_image_compress: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
