name: image_editor_plus
description: fork https://github.com/hsbijarniya/image_editor_plus 0.2.1
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.9
  screenshot: ^2.1.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.1.1
  image: ^4.1.3
  image_editor: ^1.3.0
  colorfilter_generator: ^0.0.8
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
